# Generated by Django 5.0.6 on 2024-06-05 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField(choices=[(1, 'Grupo 1'), (2, 'Grupo 2'), (3, 'Grupo 3'), (4, 'Grupo 4'), (5, 'Grupo 5')])),
                ('pistola_hk', models.IntegerField(default=0)),
                ('pistola_glock', models.IntegerField(default=0)),
                ('sub_mp5', models.IntegerField(default=0)),
                ('sub_escorpion', models.IntegerField(default=0)),
                ('fuzil_nsr', models.IntegerField(default=0)),
                ('fuzil_m4a4', models.IntegerField(default=0)),
                ('pistola_hk_municao', models.IntegerField(default=0, verbose_name='Munição Pistola HK (Preço: 1000)')),
                ('pistola_glock_municao', models.IntegerField(default=0, verbose_name='Munição Pistola Glock (Preço: 1400)')),
                ('sub_mp5_municao', models.IntegerField(default=0, verbose_name='Munição Sub MP5 (Preço: 2000)')),
                ('sub_escorpion_municao', models.IntegerField(default=0, verbose_name='Munição Sub Escorpion (Preço: 2500)')),
                ('fuzil_nsr_municao', models.IntegerField(default=0, verbose_name='Munição Fuzil NSR (Preço: 3500)')),
                ('fuzil_m4a4_municao', models.IntegerField(default=0, verbose_name='Munição Fuzil M4A4 (Preço: 4000)')),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Total')),
                ('treasurer_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor do Tesoureiro')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_id', models.IntegerField(verbose_name='ID do Comprador')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('treasurer_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('weapon_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculadora.weaponinventory')),
            ],
        ),
    ]
