# Generated by Django 5.0.3 on 2024-05-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField(choices=[(1, 'Grupo 1'), (2, 'Grupo 2'), (3, 'Grupo 3'), (4, 'Grupo 4'), (5, 'Grupo 5')])),
                ('pistola_hk', models.IntegerField(default=0, verbose_name='Pistola HK')),
                ('pistola_glock', models.IntegerField(default=0, verbose_name='Pistola Glock')),
                ('sub_mp5', models.IntegerField(default=0, verbose_name='Sub MP5')),
                ('sub_escorpion', models.IntegerField(default=0, verbose_name='Sub Escorpion')),
                ('fuzil_nsr', models.IntegerField(default=0, verbose_name='Fuzil NSR')),
                ('fuzil_m4a4', models.IntegerField(default=0, verbose_name='Fuzil M4A4')),
                ('pistola_hk_municao', models.IntegerField(default=0, verbose_name='Munição Pistola HK')),
                ('pistola_glock_municao', models.IntegerField(default=0, verbose_name='Munição Pistola Glock')),
                ('sub_mp5_municao', models.IntegerField(default=0, verbose_name='Munição Sub MP5')),
                ('sub_escorpion_municao', models.IntegerField(default=0, verbose_name='Munição Sub Escorpion')),
                ('fuzil_nsr_municao', models.IntegerField(default=0, verbose_name='Munição Fuzil NSR')),
                ('fuzil_m4a4_municao', models.IntegerField(default=0, verbose_name='Munição Fuzil M4A4')),
            ],
        ),
    ]
