# Generated by Django 5.0.3 on 2024-05-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weaponinventory',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Total'),
        ),
        migrations.AddField(
            model_name='weaponinventory',
            name='treasurer_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor do Tesoureiro'),
        ),
    ]
