# Generated by Django 5.0.3 on 2024-05-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0002_weaponinventory_total_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weaponinventory',
            name='fuzil_m4a4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weaponinventory',
            name='fuzil_m4a4_municao',
            field=models.IntegerField(default=0, verbose_name='Munição Fuzil M4A4 (Preço: 4000)'),
        ),
        migrations.AlterField(
            model_name='weaponinventory',
            name='fuzil_nsr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weaponinventory',
            name='fuzil_nsr_municao',
            field=models.IntegerField(default=0, verbose_name='Munição Fuzil NSR (Preço: 3500)'),
        ),
        migrations.AlterField(
            model_name='weaponinventory',
            name='pistola_glock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weaponinventory',
            name='pistola_glock_municao',
            field=models.IntegerField(default=0, verbose_name='Munição Pistola Glock (Preço: 1400)'),
        ),
        migrations.AlterField(
            model_name='weaponinventory',
            name='pistola_hk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weaponinventory',
            name='pistola_hk_municao',
            field=models.IntegerField(default=0, verbose_name='Munição Pistola HK (Preço: 1000)'),
        ),
        migrations.AlterField(
            model_name='weaponinventory',
            name='sub_escorpion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weaponinventory',
            name='sub_escorpion_municao',
            field=models.IntegerField(default=0, verbose_name='Munição Sub Escorpion (Preço: 2500)'),
        ),
        migrations.AlterField(
            model_name='weaponinventory',
            name='sub_mp5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weaponinventory',
            name='sub_mp5_municao',
            field=models.IntegerField(default=0, verbose_name='Munição Sub MP5 (Preço: 2000)'),
        ),
    ]
