# Generated by Django 5.0.6 on 2024-06-02 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0004_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='sale',
            name='weapon_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculadora.weaponinventory'),
        ),
    ]
